services:
  app:
    build:
      context: .
      args:
        - PORT=${PORT}
    container_name: ${PRJ_NAME}
    image: ${PRJ_NAME}-image
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./app:/app
    environment:
      - PRJ_NAME
      - CONFIG_DIR
      - PORT
    networks:
      - internal-network
networks:
  internal-network:
    external: true
